spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Desativar Swagger em producao para poupar memoria no startup
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false

# Logging minimo em producao
logging.level.root=WARN
logging.level.com.mcts.cms=INFO




