<<<<<<< HEAD
spring.datasource.url=jdbc:${DATABASE_URL}
#spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
#spring.datasource.username=${PGUSER}
#spring.datasource.password=${PGPASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
=======
#spring.datasource.url=jdbc:${DATABASE_URL}
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

>>>>>>> ea980395e54e7255ff22ec56d7c9be31d6bec001
spring.jpa.show-sql=false




