spring.application.name=cms
spring.profiles.active=${APP_PROFILE:prod}
spring.jpa.open-in-view=false

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

installment.due.interval-days=5

server.port=${PORT:8080}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Security Jwt
spring.security.jwt.token.secret-key=53cr37
spring.security.jwt.token.expire-length=3600000
spring.security.jwt.token.issuer=${APP_ISSUER:cms-api}

spring.devtools.restart.enabled=false